GS-13742 Remove Ephemeral Node on Space initialization failure
Ephemeral Node of Space instance is not removed from ZooKeeper when the Space throws
IllegalStateException: Identified another participant with the same name.